description: >-
  Write a function `valid_triangle` that takes in three side lengths (positive
  real numbers) and returns True if they can form a valid triangle, or False if
  they can't. Note: Three sides can form a triangle if adding any two sides
  always produces a larger number than the remaining third side.
topics: [conditionals]
solution: |-
  def valid_triangle(a, b, c):
      if (a + b) > c and (b + c) > a and (a + c) > b:
          return True
      else:
          return False
func: valid_triangle
args:
  - [2, 2, 2]
  - [10, 100, 20]
  - [1, 2, 3]
  - [4.8, 8.9, 13.6]
  - [5, 4, 3]
  - [9, 9, 17]
  - [10, 3, 4]
  - [4.5, 10, 4.5]
accepted: expect an email from Prof T about picking up your gift card
