description: >-
  Write a function `second_largest` that, given a list `nums`, will return the
  second highest number in `nums`,  **ignoring duplicate values**. For example,
  if `nums = [4,5,1,0,9,9,8]`, then the function should return 8. You may assume
  that `nums` will always contain at least two distinct numbers.
topics: [lists]
solution: |-
  def second_largest(nums):
      first = max(nums)
      second_diff = float('inf')
      second = None
      for num in nums:
          if first - num < second_diff and num != first:
              second = num
              second_diff = first - num

      return second
func: second_largest
args:
  - - [1, 2, 3, 4, 5, 6, 7, 8, 9]
  - - [1, 5, 7, 7]
  - - [3, 3, 4]
  - - [-1, 5, 100, 1000]
accepted: expect an email from Prof T about picking up your gift card
