description: >-
  Write a function named `thusFar` which, given a list l of length n of numbers,
  returns the list
  [k[0], k[0]+k[1], k[0]+k[1]+k[2], ..., k[0]+k[1]+...+k[n-1], k[0]+k[1]+...+k[n-1]+k[n]].
  For instance, the input [1,3,2,6] should return [1,4,6,12]
topics: [lists]
solution: |-
  def thusFar(k):
    nl=[]
    for i in k:
      if len(nl):
        nl+=[i+nl[-1]]
      else:
        nl=[i]
    return nl
func: thusFar
args:
  - - [3, 4, 5, 6]
  - - []
  - - [-1, 2, 3, 8]
  - - [4]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
