description: >-
  Write a function named `wholeCombination` that, given two numbers, returns
  True if at least one of their product, sum, or difference is a whole number.
  Return False if not. For instance, it should return True with the input pairs
  (4.3,2.7), (6,.5), and (4.3,2.3), as they have whole sum, product, and
  difference, respectively. However, the input pair (5,.5) should return False.
topics: [conditionals]
solution: |-
  def wholeCombination(a,b):
     if a*b%1==0:
       return True
     if a-b%1==0:
       return True
     if a+b%1==0:
       return True
     return False
func: wholeCombination
args:
  - [1.8, -2.8]
  - [3.6, 4.4]
  - [3.8, 4.1]
  - [3.8, 4.7]
  - [8, 0.25]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
