description: >-
  Write a function named `divisors` that, given a positive integer less than
  100000, returns a list of its divisors, ordered from least to greatest.
  Divisors that appear multiple times should only be listed once. Integer b is a
  divisor of a if there exists integer c such that b*c=a
topics: [lists]
solution: |-
  def divisors(n):
     divList=[]
     for i in range (1,int((n)**.5+1.1)):
       if n/i%1==0:
         divList = divList+ [i,int(n/i)]
         if i==n**.5:
            divList=divList[:len(divList)-1]
     return(sorted(divList))
func: divisors
args:
  - [1]
  - [2]
  - [86]
  - [83210]
  - [99999]
  - [768]
  - [65536]
  - [65535]
  - [1, 2]
accepted: expect an email from Prof T about picking up your gift card
