description: >-
  Write a function named `moveSign` that, given two numbers a and b, returns a
  with the sign of b. For instance, `moveSign(5,-8)` should return -5. However,
  if b is 0, it should return 0.
topics: [conditionals]
solution: |-
  def moveSign(a,b):
    if b==0:
      return 0
    if b*a<0:
      a*=-1
    return a
func: moveSign
args:
  - [3, 4]
  - [3, -4]
  - [-3, 4]
  - [-3, -4]
  - [8, 0]
  - [0, 8]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
