description: >-
  Write a function named `isPrime` which, given a positive integer as argument,
  checks whether it is prime. A prime number p is a number such that the only
  integer n for which p/n is a positive integer are 1 and p. The numbers to
  check will be no greater than 10^10. 1 is not prime.
topics: [lists]
solution: |-
  #in lists category because of loops
  def isPrime(n):
    if n==1:
      return False
    for i in range (2,int(n**.5)+1):
      if n/i%1==0:
        return False
    return True
func: isPrime
args:
  - [3]
  - [179424673]
  - [2]
  - [1]
  - [179424674]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
