description: >-
  Write a function named `diffchecker`. Given two lists of equal length as
  inputs, it should output a list of all of the indices at which these lists
  differ, in ascending order. For instance, given inputs [1,2,3] and [1,3,3], it
  should output [1]. Given inputs [1,3,5] and [2,4,5], it should output [0,1].
topics: [lists]
solution: |-
  def diffchecker(m,n):
    res=[]
    for i in range (0,len(m)):
      if m[i]!=n[i] or type(m[i])!=type(n[i]):
        res+=[i]
    return (res)
func: diffchecker
args:
  - - [red, blue, green]
    - [red, blue, green]
  - - []
    - []
  - - [3, 4, 5]
    - [4, 5, 6]
  - - [1, None, 2]
    - [2, 0, 3]
accepted: expect an email from Prof T about picking up your gift card
