description: >-
  Write a function named `compliment` which, given two lists as input, returns
  the list of all of the elements of the first which are not in the second, in
  the order in which they appear in the first All elements may be presumed to
  not appear more than once. For instance, given `[1,2,3,4,5]` and `[1,3,4]`,
  the function should return `[2,5]`.
topics: [lists]
solution: |-
  def compliment(a,n):
    m=[]
    for i in a:
      if not (i in n):
        m+=[i]
    return m
     
func: compliment
args:
  - - [3, 4, 5]
    - [8, -1, 4]
  - - []
    - [4, 0, 2]
  - - [1, 2]
    - [3]
  - - [1, 3, 4]
    - 4
    - 3
accepted: expect an email from Prof T about picking up your gift card
