description: >-
  Write a function named `distinct` that, given two numbers, returns True if
  they do not round to the same number (round up if the decimal part is greater
  than or equal to .5, and round down otherwise), and False if they do. For
  instance, `distinct(.4,.5)` should return True, but `distinct(.5,1.2)` should
  return False. Do not use `round`.
topics: [conditionals]
solution: |-
  def distinct(a,b):
    if a%1<.5:
      a-=a%1
    else:
      a+=1-a%1
    if b%1<.5:
      b-=b%1
    else:
      b+=1-b%1
    return (a!=b)
func: distinct
ban: [round]
args:
  - [3, 3.5]
  - [0.5, 1.4]
  - [0.5, 0.49]
  - [12, -2]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
