description: >-
  Write a function named `differences` which, given a list of more than one
  number as input, returns the list of the differences between adjacent numbers
  (for any given pair, the difference is the one to the right minus the one to
  the left). For instance, the input `[1,3,2]` should return `[2,-1]`, as 3-1=2
  and 2-3=-1.
topics: [lists]
solution: |-
  #Clarified description
  def differences(n):
    fn=n+[0]
    sn=[0]+n
    cn=zip(sn,fn)
    dn=[i[1]-i[0] for i in cn]
    return (dn[1:-1])
func: differences
args:
  - - [3, 2, 6, -3]
  - - [8, 4]
  - - [0, 1, 2, 3, 4, 5, 6, 8]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
