description: >-
  Write a function named `palindrome` which, given a list, returns True if it is
  a palindrome, and False if not. A palindrome is a list that remains the same
  if you invert its order. For instance, [2,37,2] should return True.  Do not
  use slicing, `reverse`, or `reversed`.
topics: [lists]
solution: |-
  def palindrome(n):
     for i in range(0,len(n)):
       if n[i]!=n[-(i+1)]:
         return False
     return True
func: palindrome
ban: [':', reverse, reversed]
args:
  - - [1, 2, 3]
  - - [1, 2, 1, 3, 1, 2, 1]
  - - [4, 5, 6, 5, 3]
  - - []
  - []
accepted: expect an email from Prof T about picking up your gift card
