description: >-
  Write a function named `allProducts` that, given two lists of numbers, returns
  the 2d list such that element [i][j] in the returned list is the product of
  element i in the first list and element j in the second. For instance,
  `allProducts([1,2,3],[2,4,6])` should return `[[2, 4, 6], [4, 8, 12], [6, 12,
  18]]`.
topics: [lists]
solution: |-
  def allProducts(a,b):
     m=[[0 for x in range (len(b))] for y in range (len(a))]
     for i in range (len(a)):
       for j in range (len(b)):
         m[i][j]=a[i]*b[j]
     return m
func: allProducts
args:
  - - []
    - []
  - - [1, 2, 3]
    - [4, 5, 6]
  - - [1, 2, 3, 4, 5]
    - [43432, 232]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
