description: >-
  Write a function named `mostCommon` that, given a list, returns the most
  repeated element in the list. Return None if there is no such element, or
  multiple are tied.
topics: [lists]
solution: |-
  def mostCommon(a):
    mc=None
    ct=0
    for i in a:
      if a.count(i)==ct and i!=mc and mc!=None:
        mc=None
      if a.count(i)>ct:
        ct=a.count(i)
        mc=i
    return mc
func: mostCommon
args:
  - - [1, 2, 3, 3, 2]
  - - [3, 1, 4, 1, 5, 9, 2, 6, 5, 5]
  - - []
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
