description: >-
  Write a function named `containsOrigin` that accepts real numbers x,y,a,b (in
  that order). x and y represent the x and y coordinates of the bottom left
  corner of a rectangle on the xy-plane, and a and b represent its width and
  height. Return True if (0,0) lies *within* this rectangle (lying on the edge
  does not count) and if the rectangle is valid (a and b are both positive), and
  False otherwise.
topics: [conditionals]
solution: |-
  def containsOrigin(x,y,a,b):
     if a<=0 or b<=0:
       return False
     if x>=0 or y>=0:
       return False
     if a<=-x or b<=-y:
       return False
     return True
func: containsOrigin
args:
  - [3, 4, 5, 6]
  - [0, -1, 2, 2]
  - [-2, -7, 8, 16]
  - [-1, -1, 0.5, 0.5]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
