description: >-
  Write a function named nextDate which, given two ints corresponding to month
  and date, respectively, calculates the next date, and returns its month
  multiplied by 32 plus its day. For instance, (3,31), representing March 31st,
  should return 4*32+1, representing April 1st. This is not a leap year.
topics: [conditionals]
solution: |-
  #Modified to only need single output
  def nextDate(a,b):
    b+=1
    if (a in [9,4,6,11] and b==31) or (a in [1,3,5,7,8,10,12] and b==32) or (a==2 and b==29):
      b=1
      a+=1
    if a==13:
      a=1
    return (a*32+b)
func: nextDate
args:
  - [8, 15]
  - [2, 28]
  - [9, 30]
  - [5, 31]
  - [12, 31]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
