description: >-
  Write a function named `standardize` which, given a list of lists, truncates
  elements off of the end of each of the sublists (except the
  shortest) until they are all the same length as the shortest, and returns the
  result. For instance, `standardize([[1,2,3],[4,5],[6,7,8,9]])` should return
  `[[1,2],[4,5],[6,7]]`.
topics: [lists]
solution: |-
  #clarified ambiguous wording describing truncation
  def standardize(n):
     shortestLength=float('inf')
     for i in n:
       if len(i)<shortestLength:
         shortestLength=len(i)
     for i in range (0,len(n)):
       while len(n[i])>shortestLength:
         n[i]=n[i][:-1]
     return n
func: standardize
args:
  - - - [1, 2, 3]
      - [4, 5]
      - [6, 7, 8, 9]
  - - - []
      - [1, 2, 3]
      - [4, 5]
  - - - [1, 2, 3, 4]
      - [1, 3, 4, 5]
      - [1, 2, 3, 5, 2]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
