description: >-
  Write a function named `zeroOneTwo` that, given three positive integers,
  returns True if they each have a different remainder when divided by three,
  and false if not. For instance `zeroOneTwo(8,4,12)` should return True as the
  remainders are 2, 1, and 0 (respectively), but `zeroOneTwo(8,4,13)` should
  return False, as the remainders are 2, 1, and 2, respectively.
topics: [conditionals]
solution: |-
  def zeroOneTwo(a,b,c):
     a,b,c=a%3,b%3,c%3
     if a%1 or b%1 or c%1:
       return False
     if (a+b+c)==3 and a*b*c==0:
       return True
     return False
func: zeroOneTwo
args:
  - [3, 4, 6]
  - [8, 7, 6]
  - [5, 5, 5]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
