description: >-
  Write a function named `restrict` which, given two numbers, returns the first,
  moved to a minimum distance of 1 from the second. If the first is higher and
  too close, shift up, and if they are equal or the first is lower, shift it
  down. Return the result. For instance, `restrict(4,6)=4`, `restrict(5,6)=5`,
  `restrict(5.5,6)=5`, `restrict(6,6)=5`, `restrict(6.5,6)=7`.
topics: [conditionals]
solution: |-
  def restrict(n,p):
     if n-p<1 and n-p>0:
       n=p+1
     if n-p>-1 and n-p<=0:
       n=p-1
     return n
func: restrict
args:
  - [3, 5]
  - [8, 8.5]
  - [0, 0]
  - [0, -0.1]
  - [4, hi]
accepted: expect an email from Prof T about picking up your gift card
